managment: 
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,swagger-ui"
  endpoint:
    health:
      show-details: always
  info:
    env:  
      enabled: true
    app: 
      name: "Api de Transações"
      version: 1.0.0
      description: "API para gerenciar transações e estatisticas"
    metrics:
      tag: 
        application: api-transacoes
  metrics:
    enable:
      all: true

springdoc: 
  show-actuator: true